### PR TITLE
5.3 compatability

### LINKED ISSUE #137: Fix issue with Symfony 5.3 on the 1.x branch
I migrated to ^2.0.0-alpha2. It worked for me.
I hope it will be fixed in 1.x. Because many projects depend on that version.

_Originally posted by @Chris53897 in https://github.com/liip/LiipTestFixturesBundle/issues/112#issuecomment-853377317_

### PR DESCRIPTION
**Pull request by KDederichs**
An attempt to the compatability of the 1.x branch with Symfony 5.3 changes
Fixes #137

### CODE REVIEW

**Comment by KDederichs** [comment]
Note: The test containing the ArrayCache failure will continue failing due to it trying to load doctrine cache 2.0 which removed this file.
I don’t really see a good way to keep that test from failing on newer versions without breaking it on old ones.

**Comment by KDederichs** [comment]
I also don’t know what’s with the COLUMN_STATISTICS erros, those don’t happen when I run the test locally, if anyone knows what’s up with those feel free to tell me :)

**Comment by alexislefebvre** [comment]
COLUMN_STATISTICS is due to the output of statistics when performing the backup, see a [workaround](https://github.com/liip/LiipTestFixturesBundle/pull/108/files#diff-c7e4d86841c098377a53ad88ab060d29a45bbafe76e7b5dd323d9e66a2a25e4f) in #108

**Comment by KDederichs** [comment]
Ok thanks, I added your fix here as well

**Comment by KDederichs** [comment]
Ok the only thing failing now is the missing ArrayCache adapter in doctrine.
I don’t know what you guys want to do about that one.

**Comment by mbabker** [comment]
> Ok the only thing failing now is the missing ArrayCache adapter in doctrine.
> I don’t know what you guys want to do about that one.

I don't know PHPCR-ODM all that well, but if the `DoctrinePHPCRBundle` cache configuration is similar to the ORM configuration in `DoctrineBundle`, then one option is to explicitly configure the cache to use a service or pool cache type pointing to a Symfony cache pool (since Symfony has a Doctrine Cache compatible provider).  Otherwise, I'd say skip the PHPCR-ODM tests when `doctrine/cache:>=2.0` is installed if you can't get it configured since the environment wouldn't be compatible to run it anyway.

**Comment by KDederichs** [comment]
From what I've seen all the ones they have available are Doctrine Cache based.
I can mark it skipped for now till they implement a fix.

**Comment by alexislefebvre** [comment]
Thanks for the work! Here is the release for 1.x branch: https://github.com/liip/LiipTestFixturesBundle/releases/tag/1.12.0

**Comment by phillamarmotte** [comment]
Thanks for your work

**Pull request merged**
