### PR TITLE
Symfony 5 compatibility

### PR DESCRIPTION
**Pull request by rvanlaak**

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Thanks for the PR!

In the Travis CI job, it installed `symfony/symfony:4.4.0`, it looks like something prevent installing Symfony 5. See https://travis-ci.com/liip/LiipTestFixturesBundle/jobs/259527440

Could you please add 2 lines in order to force the `^5.0` version in `.travis.yml`? You can duplicate these 2 lines then modify the last one: https://github.com/liip/LiipTestFixturesBundle/blob/59331286e9161158d41ac78605b9b2f5f018a3e0/.travis.yml#L32-L33

**Comment by rvanlaak** [comment]
Good point. Added it in e9b240be972e3570d098de8631d866c1512f2a85

**Comment by alexislefebvre** [comment]
A recent fix could also block the upgrade, if Symfony 5 requires Monolog 2: https://github.com/liip/LiipTestFixturesBundle/pull/46

**Comment by alexislefebvre** [comment]
I accidentality pushed on your branch, I removed my commit since.

**Comment by alexislefebvre** [comment]
I pushed new commits to remove unnecessary dependencies.

We'll have an error about configuration until someone fixes the CI of `theofidry/alice-data-fixtures`, see https://github.com/theofidry/AliceDataFixtures/issues/123#issuecomment-545955388

**Comment by rvanlaak** [comment]
> We'll have an error about configuration until someone fixes the CI of theofidry/alice-data-fixtures, see theofidry/AliceDataFixtures#123 (comment)

By which you mean master won't be green before that? If that's the case, what about merging this PR and tagging a release?

**Comment by alexislefebvre** [comment]
Yes, merging this PR would break the CI of this project. I can't do this, sorry.

**Comment by rvanlaak** [comment]
That then actually would make Alice a required dependency? Right now it's a dev dependency. What about moving it to `suggested` instead?

**Comment by rvanlaak** [comment]
cc @alexislefebvre 

What about making Alice a suggested dependency?

**Comment by alexislefebvre** [comment]
`loadFixtureFiles()` uses Alice: https://github.com/liip/LiipTestFixturesBundle/blob/master/doc/database.md#loading-fixtures-using-alice

I restarted the CI since there is a new release of AliceDataFixtures: https://github.com/theofidry/AliceDataFixtures/issues/123#issuecomment-560353615

**Comment by alexislefebvre** [comment]
Only the job with `composer … --prefer-lowest` fails now.

**Comment by rvanlaak** [comment]
The job that is failing does require `monolog-bridge` v2.7.0 (released in 2015). 

Given that the minimum requirement of this bundle on `monolog-bundle` is `v3.2.0` gets respected, it is that tag's requirement on the bundle that causes the problems:

https://github.com/symfony/monolog-bundle/blob/v3.2.0/composer.json#L20

What about adding `symfony/monolog-bridge:>=3` to this bundle's requirements (`v5.0.1` is [latest](https://github.com/symfony/monolog-bridge/releases))? That would remove the mismatch on the bridge and bundle versions.

**Comment by alexislefebvre** [comment]
Thanks @rvanlaak!

**Comment by alexislefebvre** [comment]
Here is the last release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/1.6.0

**Pull request merged**
