### PR TITLE
chore: Add tests for PHP 8.4

### PR DESCRIPTION
**Pull request by Chris53897**
needs update of laminas/laminas-code

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Thanks for the PR.

Let's wait for updates of the dependencies then: 

- https://github.com/laminas/laminas-code/pull/201
- https://github.com/laminas/laminas-stdlib/pull/118

**Comment by Chris53897** [comment]
Waiting for https://github.com/Seldaek/monolog/issues/1920 => DONE

**Comment by Chris53897** [comment]
The failing Testrun looks unrelated

**Comment by alexislefebvre** [comment]
Thanks!

**Comment by alexislefebvre** [comment]
> The failing Testrun looks unrelated

Running it again fixed the issue :shrug::

- fail: https://github.com/liip/LiipTestFixturesBundle/actions/runs/11800098524/job/32870210849
- OK: https://github.com/liip/LiipTestFixturesBundle/actions/runs/11800098524/job/32882895249

**Pull request merged**
