### PR TITLE
moving from env variable to --password= parameter and conditioning --…

### PR DESCRIPTION
**Pull request by dariuszp**
Command won't work on Windows. We might as well move to password.
Also port and password parameters are optional. Might be a good idea to skip them if they are empty.

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Thanks, this is interesting.

PHP evaluates `0` as `false`: https://3v4l.org/2QDYg

So no one could use `0` as a password, it seems unlikely but I think that we should use `!empty($params['password'])` to check the value.

**Comment by dariuszp** [comment]
Empty also return true with falsy values. I assumed that parameters cast
password to string every time in the process so I didn't bother to check
with strlen.



śr., 12 lut 2020, 15:00 użytkownik Alexis Lefebvre <notifications@github.com>
napisał:

**Comment by alexislefebvre** [comment]
You're right: https://3v4l.org/DNqEX

PHP sucks :stuck_out_tongue:

**Comment by alexislefebvre** [comment]
Thanks!

**Pull request merged**
