### PR TITLE
Add tests with dama/doctrine-test-bundle

### PR DESCRIPTION
**Pull request by alexislefebvre**
This is a port of https://github.com/liip/LiipFunctionalTestBundle/pull/471

See https://github.com/liip/LiipFunctionalTestBundle/issues/423

:warning: the tests should fail because of an incompatibility between this bundle and DAMADoctrineTestBundle

### CODE REVIEW

**Comment by soullivaneuh** [comment]
Maybe I'm wrong, but I don't see any fixture loading on your tests.

**Comment by alexislefebvre** [comment]
Tests are loaded from parent class: `class WebTestCaseConfigDAMADoctrineTestBundleTest extends WebTestCaseConfigMysqlTest`

**Comment by soullivaneuh** [comment]
@alexislefebvre Will it help if I can create a test symfony project with the targeted issue?

If yes, I will try to get some work time on it.

**Comment by alexislefebvre** [comment]
See #15

**Pull request closed without merging**
