### PR TITLE
2.x → master

### PR DESCRIPTION
**Pull request by alexislefebvre**
Here is the first release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/2.0.0-alpha1

### CODE REVIEW

**Comment by alexislefebvre** [comment]
@lsmith77 Hi, the current `master` is sync with the `1.x` branch that we could use for later fixes on that branch: https://github.com/liip/LiipTestFixturesBundle/tree/1.x

I think we can merge the `2.x` branch in `master` now.

**Comment by lsmith77** [comment]
didn’t we plan to drop master and keep 2.x and 1.x ?

**Comment by alexislefebvre** [comment]
Sorry, I don't remember. I thought using a `master` or `main` branch was common but https://github.com/symfony/symfony only use 4.x, 5.x, etc.

So, we can make `2.x` the default branch of that repo (I don't have the permissions) and close that PR.

**Comment by lsmith77** [comment]
and I also kill off master?

**Comment by lsmith77** [comment]
FTR 2.x is now the default branch

**Comment by alexislefebvre** [comment]
Great, thanks!

I think we don't need `master` anymore.

**Comment by lsmith77** [comment]
and its gone!

**Comment by alexislefebvre** [comment]
I updated one project from `1.x` to `2.x` successfully.

:shipit:

**Pull request closed without merging**
